#!/usr/bin/env python3
"""getbased MCP server — exposes blood work data and knowledge base search as tools.

Architecture:
  getbased (browser) → sync gateway → this MCP → your AI client
                                          ↕
                                    Lens RAG server (Qdrant + BGE-M3)

Blood work data is fetched from the getbased sync gateway.
Knowledge base queries go through the Lens RAG server (separate process).
No models are loaded in this process — everything is HTTP.
"""

import json
import os
import re

import httpx
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("getbased")

# ── Config ───────────────────────────────────────────────────────────
TOKEN = os.environ.get("GETBASED_TOKEN", "")
GATEWAY = os.environ.get("GETBASED_GATEWAY", "https://sync.getbased.health")

LENS_URL = os.environ.get("LENS_URL", f"http://localhost:{os.environ.get('LENS_PORT', '8322')}")
# Default to getbased-rag's XDG data dir (its canonical key location). The
# legacy ~/.hermes/rag/lens_api_key path is still honored when set explicitly
# via LENS_API_KEY_FILE — Hermes users running their own rag engine override
# this per their config.
_DEFAULT_KEY_PATH = os.environ.get("XDG_DATA_HOME", os.path.expanduser("~/.local/share"))
LENS_API_KEY_FILE = os.environ.get(
    "LENS_API_KEY_FILE",
    os.path.join(_DEFAULT_KEY_PATH, "getbased", "lens", "api_key"),
)


# ── Helpers ──────────────────────────────────────────────────────────

async def _fetch_context(profile: str = "") -> dict:
    """Fetch formatted lab context from the getbased sync gateway."""
    if not TOKEN:
        return {"error": "GETBASED_TOKEN not set"}
    try:
        params = {"profile": profile} if profile else {}
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.get(
                f"{GATEWAY}/api/context",
                headers={"Authorization": f"Bearer {TOKEN}"},
                params=params,
            )
            r.raise_for_status()
            return r.json()
    except httpx.HTTPStatusError as e:
        return {"error": f"getbased gateway returned {e.response.status_code}"}
    except httpx.RequestError as e:
        return {"error": f"Failed to reach getbased gateway: {e}"}


def _parse_sections(context: str) -> dict[str, str]:
    """Parse [section:name ...]...[/section:name] blocks → {full_name: content}."""
    sections = {}
    for m in re.finditer(
        r"\[section:(\S+)([^\]]*)\]([\s\S]*?)\[/section:\1\]", context
    ):
        base = m.group(1)
        meta = m.group(2).strip()
        full_name = f"{base} {meta}" if meta else base
        sections[full_name] = m.group(3).strip()
    return sections


def _read_lens_key() -> str:
    """Read the Lens API key from file (generated by lens_server.py)."""
    try:
        with open(LENS_API_KEY_FILE) as f:
            key = f.read().strip()
        return key if key else ""
    except OSError:
        return ""


async def _lens_request(query: str, top_k: int = 5) -> dict:
    """Send a query to the Lens RAG server. Returns parsed JSON or error dict."""
    key = _read_lens_key()
    if not key:
        return {"error": "Lens API key not found. Start lens_server.py first."}
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            r = await client.post(
                f"{LENS_URL}/query",
                headers={"Authorization": f"Bearer {key}"},
                json={"version": 1, "query": query, "top_k": top_k},
            )
            r.raise_for_status()
            if len(r.content) > 32 * 1024:
                return {"error": "Lens response exceeds 32 KB — possible server issue"}
            return r.json()
    except httpx.ConnectError:
        return {"error": f"Lens server not reachable at {LENS_URL}. Is it running?"}
    except httpx.HTTPStatusError as e:
        # Note: response text may contain server-side details (stack traces, DB errors)
        # Acceptable for self-hosted trust model — operator owns both ends
        return {"error": f"Lens returned {e.response.status_code}: {e.response.text}"}
    except httpx.RequestError as e:
        return {"error": f"Lens request failed: {e}"}
    except (json.JSONDecodeError, ValueError) as e:
        return {"error": f"Lens returned invalid JSON: {e}"}


async def _lens_call(method: str, path: str, json_body: dict | None = None) -> dict:
    """Generic authenticated call to the Lens server. Same error contract as
    _lens_request — every failure mode returns {"error": "..."} so tool
    callsites can uniformly forward errors to the MCP client without trying
    to catch exceptions themselves."""
    key = _read_lens_key()
    if not key:
        return {"error": "Lens API key not found. Start lens_server.py first."}
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            r = await client.request(
                method,
                f"{LENS_URL}{path}",
                headers={"Authorization": f"Bearer {key}"},
                json=json_body,
            )
            r.raise_for_status()
            return r.json() if r.content else {}
    except httpx.ConnectError:
        return {"error": f"Lens server not reachable at {LENS_URL}. Is it running?"}
    except httpx.HTTPStatusError as e:
        return {"error": f"Lens returned {e.response.status_code}: {e.response.text}"}
    except httpx.RequestError as e:
        return {"error": f"Lens request failed: {e}"}
    except (json.JSONDecodeError, ValueError) as e:
        return {"error": f"Lens returned invalid JSON: {e}"}


# ═══════════════════════════════════════════════════════════════════════
# TOOLS — Blood work data
# ═══════════════════════════════════════════════════════════════════════

@mcp.tool()
async def getbased_lab_context(profile: str = "") -> str:
    """Get a full summary of the user's blood work data, health context,
    supplements, and goals from getbased. Use when the user asks broad
    questions about their labs, biomarkers, or health trends.
    Pass a profile ID to query a specific profile, or omit for the default."""
    data = await _fetch_context(profile)
    if "error" in data:
        return f"Error: {data['error']}"
    parts = []
    if data.get("profileId"):
        parts.append(f"Profile: {data['profileId']}")
    if data.get("updatedAt"):
        parts.append(f"Updated: {data['updatedAt']}")
    parts.append(data.get("context", "No context available"))
    return "\n\n".join(parts)


@mcp.tool()
async def getbased_section(section: str = "", profile: str = "") -> str:
    """Get a specific section of health data, or list all available sections.
    Call with no section name to get the index (section names + line counts).
    Call with a section name to get just that section's content.
    Sections include: biometrics, hormones, lipids, hematology, biochemistry,
    supplements, goals, genetics, context cards, etc.
    Section names are matched by prefix.
    Pass a profile ID to query a specific profile, or omit for the default."""
    data = await _fetch_context(profile)
    if "error" in data:
        return f"Error: {data['error']}"
    context = data.get("context", "")
    if not context:
        return "No context available"

    sections = _parse_sections(context)

    if not section:
        lines = []
        for name, content in sections.items():
            count = len([l for l in content.split("\n") if l.strip()])
            lines.append(f"  {name}  ({count} lines)")
        return "Available sections:\n\n" + "\n".join(lines)

    query = section.lower().strip()
    match_key = None
    for k in sections:
        if k.lower() == query:
            match_key = k
            break
    if not match_key:
        for k in sections:
            if k.lower().startswith(query):
                match_key = k
                break
    if not match_key:
        available = [k.split(" ")[0] for k in sections]
        return f'Section "{section}" not found\nAvailable: {", ".join(available)}'

    return f"[{match_key}]\n\n{sections[match_key]}"


@mcp.tool()
async def getbased_list_profiles() -> str:
    """List all available profiles in getbased."""
    data = await _fetch_context()
    if "error" in data:
        return f"Error: {data['error']}"
    profiles = data.get("profiles") or []
    if not profiles:
        return "No profiles found"
    return "\n".join(
        f"{p.get('id', '?')}  {p.get('name', 'unnamed')}" for p in profiles
    )


# ═══════════════════════════════════════════════════════════════════════
# TOOLS — Knowledge base (RAG via Lens server)
# ═══════════════════════════════════════════════════════════════════════

@mcp.tool()
async def knowledge_search(
    query: str,
    n_results: int = 5,
    series: str = "",
    claim_type: str = "",
) -> str:
    """Search the knowledge base for relevant passages using semantic similarity.

    Searches the **currently active library** on the Lens server. If the user
    has multiple libraries (research papers, clinical guides, personal notes),
    list them with `knowledge_list_libraries` and switch with
    `knowledge_activate_library` before searching.

    Returns passages from curated health and biology research, organized by
    series and claim type. Use this when the user asks about mechanisms,
    causal relationships, or prescriptive guidance related to health topics.

    Args:
        query: Natural language search query (e.g. "folic acid MTHFR methylation")
        n_results: Number of results to return (default 5, max 10)
        series: Filter to a specific series (e.g. "Decentralized Medicine", "CPC").
            Currently no-op — placeholder for future Lens metadata filtering.
            Filter client-side from results if needed.
        claim_type: Filter to claim type: mechanism, causal, prescriptive, speculative, general.
            Currently no-op — placeholder for future Lens metadata filtering.
            Filter client-side from results if needed.
    """
    n_results = max(1, min(10, n_results))

    # TODO: series/claim_type filtering — pass to Lens when it supports metadata filters
    # Currently Lens returns top-k by relevance only. Filter client-side as needed.
    _ = series, claim_type  # acknowledge params until Lens supports them

    data = await _lens_request(query, top_k=n_results)

    if "error" in data:
        return f"Knowledge search error: {data['error']}"

    chunks = data.get("chunks", [])[:10]  # mirror web-app MAX_CHUNKS
    if not chunks:
        return "No results found for that query."

    output_lines = []
    for i, chunk in enumerate(chunks):
        text = (chunk.get("text") or "")[:4000]
        source = (chunk.get("source") or "")[:200]
        output_lines.append(f"[{i + 1}] {source}")
        output_lines.append(text)
        output_lines.append("")

    return "\n".join(output_lines)


@mcp.tool()
async def getbased_lens_config() -> str:
    """Get the Lens RAG endpoint configuration for getbased's Knowledge Base.
    Returns the URL, API key, and recommended top_k to paste into
    Settings → AI → Knowledge Base → External server in getbased.

    Note: Treat the response as sensitive — it contains the API key in plaintext."""
    key = _read_lens_key()
    if not key:
        return (
            "Lens API key not found. Start lens_server.py first to generate one.\n"
            f"Expected key file: {LENS_API_KEY_FILE}"
        )
    return (
        f"Endpoint URL: {LENS_URL}/query\n"
        f"API key (Bearer token): {key}\n"
        f"Recommended top_k: 5\n\n"
        "Paste these into getbased: Settings → AI → Knowledge Base → External server.\n"
        "For production (non-localhost), use HTTPS via a reverse proxy."
    )


@mcp.tool()
async def knowledge_list_libraries() -> str:
    """List all knowledge base libraries on the Lens server, showing which is
    active. Use this to discover what collections the user has (research
    papers, clinical guides, personal notes, etc.) before searching or
    switching between them."""
    data = await _lens_call("GET", "/libraries")
    if "error" in data:
        return f"Knowledge libraries error: {data['error']}"
    libs = data.get("libraries") or []
    active = data.get("activeId", "")
    if not libs:
        return "No libraries found. Ingest at least one document to create the default library."
    lines = ["Libraries:"]
    for lib in libs:
        lib_id = lib.get("id", "")
        name = lib.get("name", "unnamed")
        marker = "  (active)" if lib_id == active else ""
        lines.append(f"  {lib_id}  {name}{marker}")
    return "\n".join(lines)


@mcp.tool()
async def knowledge_activate_library(library_id: str) -> str:
    """Switch the Lens server's active library. All subsequent
    `knowledge_search` and `knowledge_stats` calls will target this library
    until switched again. Use `knowledge_list_libraries` first to find the ID.

    Args:
        library_id: The library's ID (not its display name). Obtained from
            knowledge_list_libraries.
    """
    if not library_id:
        return "Error: library_id is required. Call knowledge_list_libraries to find one."
    data = await _lens_call("POST", f"/libraries/{library_id}/activate")
    if "error" in data:
        return f"Activate library error: {data['error']}"
    libs = data.get("libraries") or []
    active = data.get("activeId", "")
    for lib in libs:
        if lib.get("id") == active:
            return f"Active library is now: {lib.get('name', active)} ({active})"
    return f"Active library is now: {active}"


@mcp.tool()
async def knowledge_stats() -> str:
    """Get per-source chunk counts for the active knowledge base library.
    Tells you which documents are indexed and how many excerpts each
    contributes. Useful when diagnosing "I can't find X" — either the source
    isn't indexed, or the relevant passages didn't score high enough."""
    data = await _lens_call("GET", "/stats")
    if "error" in data:
        return f"Knowledge stats error: {data['error']}"
    total = data.get("total_chunks", 0)
    docs = data.get("documents") or []
    if not docs:
        return f"Active library is empty (total chunks: {total})."
    lines = [f"Total chunks: {total}", "", "Sources:"]
    for doc in docs:
        src = doc.get("source", "unknown")
        chunks = doc.get("chunks", 0)
        lines.append(f"  {chunks:>6}  {src}")
    return "\n".join(lines)


if __name__ == "__main__":
    mcp.run()
